agents:
    trae_agent:
        enable_lakeview: true
        model: trae_agent_model
        max_steps: 50
        tools:
            - bash
            - str_replace_based_edit_tool
            - sequentialthinking
            - task_done
    code_review_agent:
        enable_lakeview: true
        model: code_review_agent_model
        max_steps: 50
        tools:
            - bash
            - str_replace_based_edit_tool
            - sequentialthinking
            - task_done
            - git_diff_tool
            - breaking_change_analyzer
            - code_analysis_tool

allow_mcp_servers:
    - playwright
mcp_servers:
    playwright:
        command: npx
        args:
            - "@playwright/mcp@0.0.27"
lakeview:
    model: lakeview_model

model_providers:
    deepseek:
        api_key: your_api_key
        provider: deepseek

models:
    trae_agent_model:
        model_provider: deepseek
        model: deepseek-chat
        max_tokens: 4096
        temperature: 0.5
        top_p: 1
        top_k: 0
        max_retries: 10
        parallel_tool_calls: true
    code_review_agent_model:
        model_provider: deepseek
        model: deepseek-chat
        max_tokens: 4096
        temperature: 0.5
        top_p: 1
        top_k: 0
        max_retries: 10
        parallel_tool_calls: true
    lakeview_model:
        model_provider: deepseek
        model: deepseek-chat
        max_tokens: 4096
        temperature: 0.5
        top_p: 1
        top_k: 0
        max_retries: 10
        parallel_tool_calls: true
